# Generated by Django 5.1.4 on 2024-12-11 23:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('numero_tlfn', models.CharField(blank=True, max_length=20, null=True)),
                ('profil', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
