# Generated by Django 5.1.4 on 2024-12-11 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_analysis', '0001_initial'),
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cosine_similarity', models.FloatField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cv_analysis.cv')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='job_offers.joboffer')),
            ],
        ),
    ]
